apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
  selector:
    app: {{.Release.Name}}
  type: {{.Values.serviceType}}
  ports:
    - protocol: TCP
      port: {{.Values.service_port}}
      targetPort: {{.Values.service_port}}
      nodePort: {{.Values.NodePort}}
